// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/2/2025, 19:01:07
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/chris/Desktop/TiendasNuestras/TN-NEW/TN-App/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/chris/Desktop/TiendasNuestras/TN-NEW/TN-App/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/chris/Desktop/TiendasNuestras/TN-NEW/TN-App/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/chris/Desktop/TiendasNuestras/TN-NEW/TN-App/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/chris/Desktop/TiendasNuestras/TN-NEW/TN-App/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/chris/Desktop/TiendasNuestras/TN-NEW/TN-App/plugins/**/*.{js,ts,mjs}","C:/Users/chris/Desktop/TiendasNuestras/TN-NEW/TN-App/composables/**/*.{js,ts,mjs}","C:/Users/chris/Desktop/TiendasNuestras/TN-NEW/TN-App/utils/**/*.{js,ts,mjs}","C:/Users/chris/Desktop/TiendasNuestras/TN-NEW/TN-App/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/chris/Desktop/TiendasNuestras/TN-NEW/TN-App/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/chris/Desktop/TiendasNuestras/TN-NEW/TN-App/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;